"""empty message

Revision ID: 04be3c5db5c6
Revises: e6e85730f241
Create Date: 2019-01-14 20:08:46.034134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04be3c5db5c6'
down_revision = 'e6e85730f241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tags',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_tags')
    # ### end Alembic commands ###
