"""empty message

Revision ID: 878238c7d878
Revises: 4df6b0ae0ea3
Create Date: 2019-01-21 15:09:47.388019

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '878238c7d878'
down_revision = '4df6b0ae0ea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('description', sa.String(length=255), nullable=True))
    op.drop_column('role', 'descriprion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('descriprion', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=True))
    op.drop_column('role', 'description')
    # ### end Alembic commands ###
